name: Dong bo code sang Landtrack B

on:
  push:
    branches:
      - main

jobs:
  sync-to-landtrack:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code tu Tai khoan A
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # Xóa quyền mặc định để dùng Token của bạn

      - name: Day code sang Tai khoan B (trongtt-landtrack)
        env:
          # Lay token moi tu Secret SYNC_TOKEN
          MY_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git config --global user.email "trongtt.landtrack@gmail.com"
          git config --global user.name "Sync Bot"
          
          # URL chuẩn để xác thực bằng Token
          DEST_REPO="https://x-access-token:${MY_TOKEN}@github.com/trongtt-landtrack/Landtrack.git"
          
          git remote add destination $DEST_REPO
          git push destination main:main --force
